name: orion_talk_cli
description: The Orion Talk Service command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  prompts: ^1.3.1
  http: ^0.12.1
  web_socket_channel: ^1.1.0


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0